[test]
levels = ["syntax", "javascript", "install", "registration", "instantiation", "execution"]

[test.workflows]
cpu = ["simple"]
cuda = "all"

[test.platforms]
platforms = ["linux", "macos", "windows", "windows_portable", "macos_desktop", "windows_desktop", "linux_cuda", "windows_cuda", "windows_portable_cuda", "windows_desktop_cuda"]
